import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

/* ============================================================================
 * LINT
 * ----------------------------------------------------------------------------
 * `npm run lint` existed in package.json and had never been able to run: no
 * eslint, no config, so `next lint` dropped into its interactive setup prompt
 * and hung. A script that cannot run is worse than no script — it reads as
 * coverage that is not there.
 *
 * eslint-config-next carries the rules that matter for this codebase: the React
 * hooks rules, and next/core-web-vitals, which is the one that would have
 * caught an <img> where a Picture belongs.
 * ========================================================================== */
const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    /* next-env.d.ts is generated by Next on every build and its triple-slash
       reference is required there, so linting it only ever produces an error
       nobody may fix. */
    ignores: ['.next/**', 'node_modules/**', 'out/**', 'public/**', 'next-env.d.ts'],
  },
  {
    rules: {
      /* A leading underscore is this codebase's existing way of saying "this
         parameter is part of the signature and deliberately unused" — see
         checkFile(file, _kind) in lib/uploads.ts. Honour the convention rather
         than making people delete the intent. */
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
      ],
    },
  },
];

export default config;
