#!/usr/bin/env node
/* ============================================================================
 * WHICH PHOTOGRAPHS ARE STILL PLACEHOLDERS
 * ----------------------------------------------------------------------------
 * Every JPEG in public/images was generated by generate-placeholders.py and
 * has "PLACEHOLDER — REPLACE WITH A REAL PHOTOGRAPH" drawn into the pixels.
 * That stamp is deliberate: it means nothing accidentally ships looking like
 * community work. It also means the live site currently says PLACEHOLDER
 * across its hero, and on a photography site that is the first thing anybody
 * sees.
 *
 * The stamp is only pixels — there is no EXIF marker to look for — so the
 * placeholders were fingerprinted instead. A file that still hashes to its
 * recorded value has not been replaced. There are no false positives: any
 * real export, at any size or quality, hashes differently.
 *
 * USAGE
 *   npm run check:images
 *
 * Exits non-zero while any placeholder remains, so it can gate a release
 * checklist. It deliberately does not gate `npm run build` — a half-finished
 * image set should not stop you deploying a security fix.
 * ========================================================================== */

import { createHash } from 'node:crypto';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'public/images');
const manifestPath = join(dir, 'placeholders.json');

if (!existsSync(manifestPath)) {
  console.error('No placeholders.json — nothing to compare against.');
  process.exit(1);
}

const { hashes } = JSON.parse(readFileSync(manifestPath, 'utf8'));
const sha = (p) => createHash('sha256').update(readFileSync(p)).digest('hex');

const still = [];
const done = [];
const missing = [];

for (const [rel, recorded] of Object.entries(hashes)) {
  const full = join(dir, rel);
  if (!existsSync(full)) { missing.push(rel); continue; }
  (sha(full) === recorded ? still : done).push(rel);
}

/* Grouped by folder, because they are replaced a folder at a time. */
const byFolder = (list) =>
  list.reduce((acc, rel) => {
    const folder = rel.includes('/') ? rel.split('/')[0] : '.';
    (acc[folder] ??= []).push(rel);
    return acc;
  }, {});

const total = Object.keys(hashes).length;
console.log(`\n  ${done.length} of ${total} replaced with real photographs\n`);

if (done.length) {
  console.log('  Real:');
  for (const [folder, files] of Object.entries(byFolder(done)))
    console.log(`    ${folder.padEnd(11)} ${files.length}`);
  console.log('');
}

if (still.length) {
  console.log('  Still placeholders:');
  for (const [folder, files] of Object.entries(byFolder(still))) {
    console.log(`    ${folder}`);
    for (const f of files) console.log(`      ${f.split('/').pop()}`);
  }
  console.log('\n  Keep the filenames and drop your exports in — ~2400px on the');
  console.log('  long edge, and hero/pune-hero.jpg under ~250 kB because it is the');
  console.log('  only image loaded with priority. next/image handles the rest.\n');
}

if (missing.length) {
  console.log('  Missing entirely (the page will 404 the image):');
  for (const f of missing) console.log(`    ${f}`);
  console.log('');
}

process.exit(still.length || missing.length ? 1 : 0);
